// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.590
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Menu() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary\"><div class=\"offcanvas-md offcanvas-end bg-body-tertiary\" tabindex=\"-1\" id=\"sidebarMenu\" aria-labelledby=\"sidebarMenuLabel\"><div class=\"offcanvas-header\"><h5 class=\"offcanvas-title\" id=\"sidebarMenuLabel\">Studipaasdadsy</h5><button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" data-bs-target=\"#sidebarMenu\" aria-label=\"Close\"></button></div><div class=\"offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto\"><ul class=\"nav flex-column\"><li class=\"nav-item\"><a class=\"nav-link d-flex align-items-center gap-2 active\" aria-current=\"page\" href=\"#\"><svg class=\"bi\"><use xlink:href=\"#house-fill\"></use></svg> Dashboard</a></li><li class=\"nav-item\"><a class=\"nav-link d-flex align-items-center gap-2\" href=\"#\"><svg class=\"bi\"><use xlink:href=\"#file-earmark\"></use></svg> Pagos</a></li><li class=\"nav-item\"><a class=\"nav-link d-flex align-items-center gap-2\" href=\"#\"><svg class=\"bi\"><use xlink:href=\"#people\"></use></svg> Estudiantes</a></li></ul><hr class=\"my-3\"><ul class=\"nav flex-column mb-auto\"><li class=\"nav-item\"><a class=\"nav-link d-flex align-items-center gap-2\" href=\"#\"><svg class=\"bi\"><use xlink:href=\"#gear-wide-connected\"></use></svg> Settings</a></li><li class=\"nav-item\"><a class=\"nav-link d-flex align-items-center gap-2\" href=\"#\"><svg class=\"bi\"><use xlink:href=\"#door-closed\"></use></svg> Sign out</a></li></ul></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
